In [ ]:
#### 1. Import the numpy package under the name `np` (★☆☆)


In [4]:
import numpy as np

In [ ]:
#### 2. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
null_vector_1 = np.array([0,0,0,0,0,1,0,0,0,0])
print(null_vector_1)

[0 0 0 0 0 1 0 0 0 0]


In [ ]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
new_vector = np.arange(10,50)
print(new_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
new_matrix = np.arange(0, 9).reshape((3, 3))
print(new_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
a = [1,2,0,0,4,0]
b =np.nonzero(a)
print(b)

(array([0, 1, 4], dtype=int64),)


In [ ]:
#### 7. Create a 3x3 identity matrix (★☆☆)

In [18]:
c = np.eye(3,3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#### 8. Create a 3x3x3 array with random values (★☆☆)

In [23]:
d = np.random.random((3,3,3))
print(d)

[[[0.38344152 0.79172504 0.52889492]
  [0.56804456 0.92559664 0.07103606]
  [0.0871293  0.0202184  0.83261985]]

 [[0.77815675 0.87001215 0.97861834]
  [0.79915856 0.46147936 0.78052918]
  [0.11827443 0.63992102 0.14335329]]

 [[0.94466892 0.52184832 0.41466194]
  [0.26455561 0.77423369 0.45615033]
  [0.56843395 0.0187898  0.6176355 ]]]


In [ ]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [6]:
e = np.random.random((5,5))
print(e)

[[0.60704114 0.8328009  0.87647122 0.69012365 0.62879222]
 [0.7138075  0.75569989 0.57210482 0.31990133 0.59581101]
 [0.35247379 0.70604965 0.26942922 0.45354241 0.35958114]
 [0.5605431  0.13293228 0.26656747 0.48685783 0.21631491]
 [0.65848842 0.21288726 0.06236508 0.28319177 0.49206955]]


In [29]:
#min val
f = np.amin(e)
print(f)

0.019193198309333526


In [30]:
#max val
g = np.amax(e)
print(g)

0.9560836347232239


In [ ]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [31]:
h = np.random.random((6,5))
print(h)

[[0.57432525 0.65320082 0.65210327 0.43141844 0.8965466 ]
 [0.36756187 0.43586493 0.89192336 0.80619399 0.70388858]
 [0.10022689 0.91948261 0.7142413  0.99884701 0.1494483 ]
 [0.86812606 0.16249293 0.61555956 0.12381998 0.84800823]
 [0.80731896 0.56910074 0.4071833  0.069167   0.69742877]
 [0.45354268 0.7220556  0.86638233 0.97552151 0.85580334]]


In [32]:
#mean value 
np.mean(h)

0.6112261397292997

In [ ]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [5]:
j = np.diag(np.arange(1,5),k =-1)
print(j)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#### 12. Normalize a 5x5 random matrix (★☆☆)

In [17]:
k = np.random.random((5,5))
print(k)
l = np.mean(k)
#print(l)
m = np.std(k)

[[0.88850572 0.14846672 0.1838655  0.98757434 0.05536111]
 [0.57253715 0.98467826 0.54264817 0.06840955 0.11506625]
 [0.70680373 0.32462352 0.45196492 0.50968001 0.77652705]
 [0.98815799 0.80690867 0.9032439  0.06887155 0.18437728]
 [0.320846   0.72057362 0.22723068 0.59390622 0.22221088]]


In [18]:
n = (k-l)/m
print(n)

[[ 1.23255258 -1.08026077 -0.96963045  1.54216765 -1.37123989]
 [ 0.24506905  1.53311665  0.15165824 -1.33046015 -1.18464589]
 [ 0.66468682 -0.5297252  -0.1317504   0.04862419  0.88259024]
 [ 1.5439917   0.97754069  1.27861318 -1.32901629 -0.968031  ]
 [-0.54153093  0.7077213  -0.83410304  0.3118529  -0.84979119]]


In [ ]:
#### 13. How to find common values between two arrays? (★☆☆)

In [29]:
o = np.arange(0,9).reshape(3, 3)
p = np.arange(7,16).reshape(3,3)
print(o, "\n")
print(p)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [30]:
np.intersect1d(o, p)

array([7, 8])

In [ ]:
#### 14. Create a random vector of size 10 and sort it (★★☆)

In [39]:
r = np.random.random(10)
print(r)

[0.96549239 0.35430795 0.9279083  0.47175094 0.15219023 0.83370561
 0.5261954  0.53231226 0.4839792  0.04928771]


In [40]:
np.sort(r)

array([0.04928771, 0.15219023, 0.35430795, 0.47175094, 0.4839792 ,
       0.5261954 , 0.53231226, 0.83370561, 0.9279083 , 0.96549239])

In [ ]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [53]:
s = np.random.random(10)
print(s)

[0.907146   0.38378635 0.92368516 0.55620784 0.44455617 0.47562555
 0.29095809 0.65213988 0.43351911 0.95415636]


In [56]:
s[s.argmax()]=0
s

array([0.907146  , 0.38378635, 0.        , 0.55620784, 0.44455617,
       0.47562555, 0.29095809, 0.65213988, 0.43351911, 0.        ])

In [ ]:
#### 16. Subtract the mean of each row of a matrix (★★☆)

In [63]:
t = np.random.rand(3,3)
print(t)

[[0.90274984 0.16634418 0.56168107]
 [0.11670586 0.15211499 0.90614594]
 [0.4248357  0.6075144  0.4315169 ]]


In [65]:
t -= np.mean(t, axis = 1, keepdims = True)
print(t)

[[ 0.35915814 -0.37724751  0.01808937]
 [-0.27494974 -0.23954061  0.51449034]
 [-0.06311997  0.11955874 -0.05643877]]


In [ ]:
#### 17. How to get the n largest values of an array (★★★)

In [ ]:
#Z = np.arange(10000)
#np.random.shuffle(Z)
#n = 5
#hint: np.argsort | np.argpartition

In [80]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

In [81]:
print(Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [ ]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 

In [94]:
w = np.random.rand(5,3)
print(w)

[[0.71212995 0.85019677 0.85823126]
 [0.30165885 0.0554705  0.16013749]
 [0.78089272 0.42454404 0.54324838]
 [0.25685382 0.02369191 0.24238906]
 [0.34274148 0.76487287 0.19688906]]


In [95]:

y = np.where(w < 4, w**2, w)
print(y)

[[5.07129067e-01 7.22834546e-01 7.36560903e-01]
 [9.09980631e-02 3.07697610e-03 2.56440156e-02]
 [6.09793439e-01 1.80237638e-01 2.95118805e-01]
 [6.59738871e-02 5.61306375e-04 5.87524565e-02]
 [1.17471719e-01 5.85030513e-01 3.87653027e-02]]
