In [ ]:
#### 1. Import the numpy package under the name `np` (★☆☆)


In [1]:
import numpy as np

In [ ]:
#### 2. Create a null vector of size 10 (★☆☆)

In [2]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [3]:
null_vector_1 = np.array([0,0,0,0,0,1,0,0,0,0])
print(null_vector_1)

[0 0 0 0 0 1 0 0 0 0]


In [ ]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
new_vector = np.arange(10,50)
print(new_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [5]:
new_matrix = np.arange(0, 9).reshape((3, 3))
print(new_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
a = [1,2,0,0,4,0]
b =np.nonzero(a)
print(b)

(array([0, 1, 4], dtype=int64),)


In [ ]:
#### 7. Create a 3x3 identity matrix (★☆☆)

In [18]:
c = np.eye(3,3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#### 8. Create a 3x3x3 array with random values (★☆☆)

In [23]:
d = np.random.random((3,3,3))
print(d)

[[[0.38344152 0.79172504 0.52889492]
  [0.56804456 0.92559664 0.07103606]
  [0.0871293  0.0202184  0.83261985]]

 [[0.77815675 0.87001215 0.97861834]
  [0.79915856 0.46147936 0.78052918]
  [0.11827443 0.63992102 0.14335329]]

 [[0.94466892 0.52184832 0.41466194]
  [0.26455561 0.77423369 0.45615033]
  [0.56843395 0.0187898  0.6176355 ]]]


In [ ]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [6]:
e = np.random.random((10,10))
print(e)

[[0.89356273 0.03753486 0.46773718 0.49844967 0.76725796 0.06672267
  0.17318553 0.43820365 0.80036683 0.22556948]
 [0.06866158 0.91861721 0.86595397 0.65202513 0.81685621 0.78386039
  0.20043423 0.38265389 0.53165418 0.29190337]
 [0.51639554 0.04634539 0.29286932 0.86008512 0.94315696 0.38315854
  0.66594273 0.77185968 0.24496197 0.23744249]
 [0.46185373 0.52654592 0.18961421 0.20735215 0.49865079 0.76294446
  0.36534336 0.99166931 0.58270468 0.29074253]
 [0.99767027 0.63479896 0.84676351 0.85113874 0.69677936 0.64515094
  0.16762549 0.59599992 0.45568888 0.45955771]
 [0.7445004  0.20688814 0.63743613 0.96599994 0.75237384 0.59013401
  0.44604309 0.82478122 0.29029659 0.67301418]
 [0.96663109 0.8190817  0.03882852 0.6866433  0.13667042 0.88060469
  0.64568457 0.55121478 0.03509015 0.3561311 ]
 [0.60549505 0.99924612 0.81899953 0.97547562 0.13600304 0.18228821
  0.64390709 0.31392557 0.79674142 0.20328246]
 [0.37239169 0.61001136 0.11988498 0.14475149 0.89787791 0.93357171
  0.24813563

In [29]:
#min val
f = np.amin(e)
print(f)

0.019193198309333526


In [30]:
#max val
g = np.amax(e)
print(g)

0.9560836347232239


In [ ]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [8]:
h = np.random.random((6,5))
print(h)

[[0.82140354 0.17307466 0.98870148 0.23581198 0.76527002]
 [0.60898767 0.90553168 0.14212246 0.52031245 0.04139835]
 [0.22101559 0.28752471 0.34158165 0.23887088 0.27495661]
 [0.13207626 0.8982878  0.51397144 0.18774107 0.07061577]
 [0.3285516  0.26828992 0.3983015  0.19759814 0.20861323]
 [0.52840415 0.63139331 0.9207324  0.78945832 0.42902741]]


In [32]:
#mean value 
np.mean(h)

0.6112261397292997

In [ ]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [10]:
j = np.diag(np.arange(1,5),k =-1)
print(j)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#### 12. Normalize a 5x5 random matrix (★☆☆)

In [13]:
k = np.random.random((5,5))
print(k)
l = np.mean(k)
#print(l)
m = np.std(k)

[[0.95879358 0.7931379  0.39350294 0.78926174 0.6541358 ]
 [0.26171826 0.97912731 0.00934988 0.61566251 0.55464566]
 [0.59160611 0.6576305  0.571707   0.59805664 0.24388142]
 [0.44728844 0.4639261  0.68517465 0.4298789  0.34531541]
 [0.13618189 0.0159563  0.8287384  0.01157683 0.38723266]]


In [14]:
matrix = (k - np.mean(k)/np.std(k))

In [18]:
n = (k-l)/m
print(n)

[[ 1.23255258 -1.08026077 -0.96963045  1.54216765 -1.37123989]
 [ 0.24506905  1.53311665  0.15165824 -1.33046015 -1.18464589]
 [ 0.66468682 -0.5297252  -0.1317504   0.04862419  0.88259024]
 [ 1.5439917   0.97754069  1.27861318 -1.32901629 -0.968031  ]
 [-0.54153093  0.7077213  -0.83410304  0.3118529  -0.84979119]]


In [ ]:
#### 13. How to find common values between two arrays? (★☆☆)

In [29]:
o = np.arange(0,9).reshape(3, 3)
p = np.arange(7,16).reshape(3,3)
print(o, "\n")
print(p)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [30]:
np.intersect1d(o, p)

array([7, 8])

In [ ]:
#### 14. Create a random vector of size 10 and sort it (★★☆)

In [39]:
r = np.random.random(10)
print(r)

[0.96549239 0.35430795 0.9279083  0.47175094 0.15219023 0.83370561
 0.5261954  0.53231226 0.4839792  0.04928771]


In [40]:
np.sort(r)

array([0.04928771, 0.15219023, 0.35430795, 0.47175094, 0.4839792 ,
       0.5261954 , 0.53231226, 0.83370561, 0.9279083 , 0.96549239])

In [ ]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [53]:
s = np.random.random(10)
print(s)

[0.907146   0.38378635 0.92368516 0.55620784 0.44455617 0.47562555
 0.29095809 0.65213988 0.43351911 0.95415636]


In [56]:
s[s.argmax()]=0
s

array([0.907146  , 0.38378635, 0.        , 0.55620784, 0.44455617,
       0.47562555, 0.29095809, 0.65213988, 0.43351911, 0.        ])

In [ ]:
#### 16. Subtract the mean of each row of a matrix (★★☆)

In [63]:
t = np.random.rand(3,3)
print(t)

[[0.90274984 0.16634418 0.56168107]
 [0.11670586 0.15211499 0.90614594]
 [0.4248357  0.6075144  0.4315169 ]]


In [65]:
t -= np.mean(t, axis = 1, keepdims = True)
print(t)

[[ 0.35915814 -0.37724751  0.01808937]
 [-0.27494974 -0.23954061  0.51449034]
 [-0.06311997  0.11955874 -0.05643877]]


In [ ]:
#### 17. How to get the n largest values of an array (★★★)

In [ ]:
#Z = np.arange(10000)
#np.random.shuffle(Z)
#n = 5
#hint: np.argsort | np.argpartition

In [23]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(Z)

[6002 6050 4501 ... 6517 6971 1652]


In [20]:
print(Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [21]:
print(Z[np.argpartition(-Z,n)[:n]])

[9998 9999 9997 9996 9995]


In [ ]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 

In [30]:
w = np.random.random((5,3))
print(w)

[[0.92241184 0.55291101 0.71748347]
 [0.47232077 0.73562999 0.597057  ]
 [0.77454304 0.80817059 0.79108895]
 [0.59901036 0.21909577 0.37112912]
 [0.99345751 0.34971949 0.02823405]]


In [31]:
y = np.where(w > 4, w**2, w)
print(y)

[[0.92241184 0.55291101 0.71748347]
 [0.47232077 0.73562999 0.597057  ]
 [0.77454304 0.80817059 0.79108895]
 [0.59901036 0.21909577 0.37112912]
 [0.99345751 0.34971949 0.02823405]]
